kern.* stop
#*.info stop
:programname, isequal, "wpa_supplicant" stop
:programname, isequal, "NetworkManager" stop
:programname, isequal, "systemd-resolved" stop
:msg, contains, "wl" stop
:msg, contains, "interface" stop
